# Override Netdata's stock CPU alert for this VPS.
# The value is the average non-idle CPU utilization over the preceding 10 minutes.
template: 10min_cpu_usage
      on: system.cpu
   class: Utilization
    type: System
component: CPU
  lookup: average -10m unaligned of user,system,softirq,irq,guest
   units: %
   every: 1m
    warn: $this > 60
    crit: $this > 70
 summary: CPU utilization
    info: Average CPU utilization exceeded 60% for the last 10 minutes
      to: sysadmin
